TYPE Form
    x AS INTEGER
    y AS INTEGER
    w AS INTEGER
    h AS INTEGER
    title AS STRING
    isFocus AS INTEGER
END TYPE

TYPE Button
	x AS INTEGER
    y AS INTEGER
    w AS INTEGER
    h AS INTEGER
	label AS STRING
	isClicked AS INTEGER
END TYPE